default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  username: beetrackuser
  password: beetrack
  pool: 5

development:
  <<: *default
  database: beetrack_db_development

test:
  <<: *default
  database: beetrack_db_tests